<?php

/**
 * @file
 * Slick slider for Drupal.
 */

/**
 * Implements hook_theme().
 */
function slick_theme() {
  $base = array(
    'file' => 'templates/slick.theme.inc',
  );
  return array(
    // Slick display.
    'slick' => $base + array(
      'render element' => 'elements',
    ),
    // Individual slick item.
    'slick_slide' => $base + array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_library_info_build().
 */
function slick_library_info_build() {
  $libraries['slick.css'] = [
    'dependencies' => ['slick/slick'],
    'css' => [
      'theme' => ['/libraries/slick/slick/slick-theme.css' => []],
    ],
  ];

  foreach (\Drupal::service('slick.manager')->getAvailableSkins() as $group => $skins) {
    foreach ($skins as $key => $skin) {
      $provider = isset($skin['provider']) ? $skin['provider'] : 'slick';
      $id = $provider . '.' . $group . '.' . $key;
      if (isset($skin['css']) && is_array($skin['css'])) {
        $libraries[$id]['css'] = $skin['css'];
      }
      if (isset($skin['js']) && is_array($skin['js'])) {
        $libraries[$id]['js'] = $skin['css'];
      }
    }
  }
  return $libraries;
}

/**
 * Implements hook_hook_info().
 *
 * @deprecated, will be removed anytime when a core solution is available.
 * @see https://drupal.org/node/2233261
 */
function slick_hook_info() {
  $hooks['slick_skins_info'] = ['group' => 'slick'];
  return $hooks;
}
