<?php
/**
 * @file
 * Provides the Slick carousel export UI.
 */

/**
 * Implements hook_menu().
 */
function slick_ui_menu() {
  $items['admin/config/media/slick'] = array(
    'title' => 'Slick carousel',
    'description' => 'Create and manage Slick carousel optionsets.',
    'page callback' => 'slick_ui',
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );
  $items['admin/config/media/slick/list'] = array(
    'title' => 'Optionsets',
    'description' => 'Create and manage Slick carousel optionsets.',
    'page callback' => 'slick_ui',
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/media/slick/ui'] = array(
    'title' => 'Settings',
    'description' => 'Configure the Slick user interface.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('slick_ui_form_settings'),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  $items['admin/config/media/slick/add'] = array(
    'title' => 'Add Slick Optionset',
    'description' => 'Create a Slick carousel Optionset',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('slick_ui_edit_form'),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/config/media/slick/%slick_optionset/configure'] = array(
    'title' => 'Configure optionset',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('slick_ui_edit_form', 4),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/media/slick/%slick_optionset/enable'] = array(
    'title' => 'Enable optionset',
    'load arguments' => array(TRUE),
    'page callback' => 'slick_optionset_enable',
    'page arguments' => array(4),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/media/slick/%slick_optionset/disable'] = array(
    'title' => 'Disable optionset',
    'page callback' => 'slick_optionset_disable',
    'page arguments' => array(4),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/media/slick/%slick_optionset/delete'] = array(
    'title' => 'Delete optionset',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('slick_ui_delete_form', 4),
    'access arguments' => array('administer slick'),
    'file' => 'slick_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function slick_ui_permission() {
  return array(
    'administer slick' => array(
      'title' => t('Administer the Slick carousel module'),
    ),
  );
}

/**
 * Implements hook_library().
 */
function slick_ui_library() {
  $path = backdrop_get_path('module', 'slick');
  $info = system_get_info('module', 'slick_ui');

  $libraries['slick.ui'] = array(
    'title' => 'Slick UI',
    'website' => 'http://drupal.org/project/slick_ui',
    'version' => !empty($info['version']) ? $info['version'] : '7.x-2.x',
    'js' => array(
      $path . '/js/slick.admin.ui.min.js' => array('group' => JS_DEFAULT, 'weight' => 3),
    ),
    'css' => array(
      $path . '/css/admin/slick.admin--ui--field.css' => array('group' => CSS_THEME + 1),
      $path . '/css/admin/slick.admin--ui.css' => array('group' => CSS_THEME + 1, 'weight' => 9),
    ),
  );

  return $libraries;
}
