<?php
/**
 * @file
 * Provides the Slick carousel export UI.
 */

/**
 * Implements hook_menu().
 */
function slick_ui_menu() {
  $items['admin/config/media/slick/ui'] = array(
    'title' => 'UI',
    'description' => 'Configure the Slick UI.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('slick_ui_form_settings'),
    'access arguments' => array('administer slick'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function slick_ui_library() {
  $path = backdrop_get_path('module', 'slick');
  $info = system_get_info('module', 'slick_ui');

  $libraries['slick.ui'] = array(
    'title' => 'Slick UI',
    'website' => 'http://drupal.org/project/slick_ui',
    'version' => !empty($info['version']) ? $info['version'] : '7.x-2.x',
    'js' => array(
      $path . '/js/slick.admin.ui.min.js' => array('group' => JS_DEFAULT, 'weight' => 3),
    ),
    'css' => array(
      $path . '/css/admin/slick.admin--ui--field.css' => array('group' => CSS_THEME + 1),
      $path . '/css/admin/slick.admin--ui.css' => array('group' => CSS_THEME + 1, 'weight' => 9),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_permission().
 */
function slick_ui_permission() {
  return array(
    'administer slick' => array(
      'title' => t('Administer the Slick carousel module'),
    ),
  );
}

/**
 * Form for Slick UI module settings.
 */
function slick_ui_form_settings() {
  $config = config('slick.settings');
  $form['slick_admin_css'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable Slick admin CSS'),
    '#description'   => t('Uncheck if trouble with slick admin CSS compatibility for your admin theme.'),
    '#default_value' => $config->get('admin_css'),
  );

  $form['slick_module_css'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable Slick module slick.theme.css'),
    '#description'   => t('Uncheck to permanently disable the module slick.theme.css, normally included along with skins.'),
    '#default_value' => $config->get('module_css'),
  );

  $form['slick_css'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable Slick library slick-theme.css'),
    '#description'   => t('Uncheck to permanently disable the optional slick-theme.css, normally included along with skins.'),
    '#default_value' => $config->get('slick_css'),
  );

  return system_settings_form($form);
}
